### ISSUE TITLE
[PE-D][Tester D] Meeting Display Ordering not chronological

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W09-4/tp#134]
I would expect that the display for meetings is in chronological order however, meeting 1 occurs before meeting 2. and meeting 2 occurs after meeting 3. 

This is the default display upon launching the app.

![image.png](https://raw.githubusercontent.com/yashma-sonara/ped/main/files/4b3f85cb-0286-44df-afe0-71b67fc1a30e.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: yashma-sonara/ped#1

**Comment by jimseah-0116** [comment]
Duplicate issue #154
