### ISSUE TITLE
[PE-D][Tester D] Meetings command does not display

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W09-4/tp#136]
In the default display, (before any commands were entered), I can see 6 meetings present. But when I use the command `meetings`, the popup shows no meetings listed.

![image.png](https://raw.githubusercontent.com/yashma-sonara/ped/main/files/1edbc6a1-2935-447d-b020-e43e92184f17.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: yashma-sonara/ped#2

**Comment by irwynliong** [comment]
We already stated that the view meeting function is only for the week and not the whole list.
i.e If there is a meeting this week, it will show that there is a meeting.
Please read our UG carefully before saying its a flaw
