### ISSUE TITLE
[PE-D][Tester B] Policies box UI does not update when adding new policies

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W09-4/tp#140]
In the UI, there's a box designated for policies, which most users should assume that whenever a new policy is added to a client, then the list of policies will be added. However the policy box remains empty even after adding multiple policies. The user is then unable to keep track of the details of the policies that they have added, such as the policy_type, policy_id, premium_term, policy_premium, and benefit as only the policy_name is shown in the clients.

![image.png](https://raw.githubusercontent.com/Ryan-Reno/ped/main/files/5d103a6f-12bd-4dcc-adfd-ce5ed59a8632.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Ryan-Reno/ped#2

**Comment by jimseah-0116** [comment]
Policy list panel shows:
1) A single policy (when added with `addpolicy`)
2) List of policies (when using `view`)

Should not show anything, for other commands

**Comment by jimseah-0116** [comment]
EDIT: I don't think we should change the addPolicy command, as this will violate feature freeze. We should specify clearly in the UG that users will need to use 'view' command to verify the details of the just-added policy.
This fix can be put under "planned enhancements" in DG.
