### ISSUE TITLE
[PE-D][Tester D] Meeting date constraint 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W09-4/tp#151]
I think there should be some constraint on date of meeting. When adding H, I choose a meeting date in year 3020 which is illogical. 

![image.png](https://raw.githubusercontent.com/yashma-sonara/ped/main/files/72aaf7e2-1f46-4c24-a198-a52ca7b58585.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: yashma-sonara/ped#8

**Comment by irwynliong** [comment]
its not an issue
