### ISSUE TITLE
[PE-D][Tester B] Name cannot handle special characters

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W09-4/tp#152]
add n/Jenny-Chen p/91234567 e/jenjenc@gmail.com a/688, Yio Chu Kang Ave 5, #04-25 m/2024-10-12 14:00
edit 1 n/jenny,chen

Running these 2 commands will result in the same warning: Names should only contain alphanumeric characters and spaces, and it should not be blank. However it is not documented in the user guide that names can only be alphanumeric. 

Moreover, symbols with , or / are not uncommon in names, especially in countries such as hong kong.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Ryan-Reno/ped#5

**Comment by jimseah-0116** [comment]
Shall we allow any name that isn't whitespace? I'm not sure what characters to allow for names 🤔

**Comment by jimseah-0116** [comment]
Not fixing.

Clearly state that name should be alphanumeric characters only in UG. Also mention that names like "al-Assad" can be input as "al Assad" (not a perfect workaround, but as long as the user can identify the client, it should be ok). Can mention that we are working to allow special characters in future release versions.

Justification: If we allow special characters, which ones should we allow? Some names might have very uncommon special characters. If we allow all special characters, names such as "@#*$" will be allowed, which is unintended behavior.
