### ISSUE TITLE
[PE-D][Tester A] Inputting Invalid Date Does Not Prevent Creation of Meeting

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W09-4/tp#153]
Invalid Date(2025-04-31 14:00) is still allowed in creation of meeting

Input
add n/Test Name 7 p/123 e/email@email a/what m/2025-04-31 14:00

![image.png](https://raw.githubusercontent.com/JerryO3/ped/main/files/22a8d00f-5b4f-4042-8d3e-0208d1205f41.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: JerryO3/ped#3

**Comment by jimseah-0116** [comment]
Justification: Allowed to fix because this issue affects our `meetings` command, which is specified in our UG to "display all meetings for the week". This issue may cause some invalid dates to either appear or not appear in the Meetings window, depending on the day of the week.
