### ISSUE TITLE
[PE-D][Tester C] User Guide has limited amount of screenshots 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W09-4/tp#155]
Upon reviewing the user guide for the first time, I encountered some challenges in understanding its content. Specifically, I noticed that there was only one screenshot illustrating the interface, which made it difficult to grasp the functionality effectively. It would greatly enhance user comprehension if there were multiple screenshots included, particularly demonstrating the usage of commands like addpolicy and delpolicy, which are unique contributions from your team.

![Screenshot 2024-04-05 at 4.48.12 PM.png](https://raw.githubusercontent.com/eunrcn/ped/main/files/fb3ebf64-79f9-4d0c-900c-beb01ece13ee.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: eunrcn/ped#5

**Comment by jimseah-0116** [comment]
Add screenshots for policy-related commands to show the 'Policies' panel in action.

Good to do as well: Update screenshot in "Quick Start" to label the different parts in our UI - input line, user feedback box, etc.
