### ISSUE TITLE
[PE-D][Tester B] Names are case-sensitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W09-4/tp#160]
add n/Jenny Chen p/91234567 e/jenjenc@gmail.com a/688, Yio Chu Kang Ave 5, #04-25 m/2024-10-12 14:00
add n/Jenny chen p/91234567 e/jenjenc@gmail.com a/688, Yio Chu Kang Ave 5, #04-25 m/2024-05-12 14:00

Running these two commands will result in creating two clients, although the phone number, email, and address are exactly the same, meaning that these two people should be the same person. Names in general should not be case-sensitive as different capitalization do not refer to a different person

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Ryan-Reno/ped#7

**Comment by irwynliong** [comment]
same as #194
