### ISSUE TITLE
[PE-D][Tester D] view Policy details issue

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W09-4/tp#163]
Adding a policy requires many details (pol/POLICY_NAME type/POLICY_TYPE polnum/POLICY_ID). 
However the only way to view details is to view a student with said policy.

I would expect there to be a command to view details or display details of a policy more easily.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: yashma-sonara/ped#10

**Comment by jimseah-0116** [comment]
Same as #140 :
Allow users to see the policy details when they use `addpolicy`
