### ISSUE TITLE
[PE-D][Tester A] Unable to see the full names of people with long names

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W09-4/tp#165]
As described, a very small feature flaw as there is no way to see the full name.

Input:
Add a very long name as string in add command

![image.png](https://raw.githubusercontent.com/JerryO3/ped/main/files/6b29c194-6195-4215-b687-cebe3c2eccff.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: JerryO3/ped#6

**Comment by irwynliong** [comment]
limit characters for name
