### ISSUE TITLE
[PE-D][Tester B] Inconsistency in error message and user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W09-4/tp#171]
addPolicy 1 pol/SuperSaver type/CI polnum/39376234 pterm/Annually prem/3000 b/100000

Running this command twice will result in the following error message:
The client already has this policy number

However, the user guide refers it as POLICY_ID, which may cause confusion for users

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Ryan-Reno/ped#9

**Comment by jimseah-0116** [comment]
I've fixed this in PR #198
