### ISSUE TITLE
[PE-D][Tester D] delPolicy UG command format wrong

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W09-4/tp#180]
The command format for delPolicy is wrong as it does not have the required INDEX value, as seen in the command examples. 

![image.png](https://raw.githubusercontent.com/yashma-sonara/ped/main/files/f972bae4-79e7-447e-a07d-3894dfd885ea.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: yashma-sonara/ped#12

**Comment by youdonnnn** [comment]
same as #193
