### ISSUE TITLE
[PE-D][Tester B] POLICY_NUMBER is a String

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W09-4/tp#181]
In the user guide for delPolicy command, the description says that POLICY_NUMBER is a String.

A person who is not tech-savvy will be confused as to what this actually means. Furthermore, it also contradicts the field name as the field name is stated as a number, but then it is a string

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Ryan-Reno/ped#12

**Comment by jimseah-0116** [comment]
Fixed: UG now specifies "alphanumeric characters" for POLICY_NUMBER.
