### ISSUE TITLE
[PE-D][Tester A] Deleting a client on the list does not delete the meeting with the client

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W09-4/tp#182]
Deleting a client on the list does not delete the meeting with the client, but instead deletes the same indexed meeting on the meeting view!

Input
filter Irfan
delete 1

Before deleting
![image.png](https://raw.githubusercontent.com/JerryO3/ped/main/files/5af8c053-bfb0-4685-bd13-f2bcd35df0f6.png)

After deleting
![image.png](https://raw.githubusercontent.com/JerryO3/ped/main/files/2d22a46e-0a12-43ae-bd5b-36d18632455e.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: JerryO3/ped#12

**Comment by irwynliong** [comment]
same as #196
