### ISSUE TITLE
Add 'meetings' command

### ISSUE THREAD

**Issue by irwynliong** [AY2324S2-CS2103T-W09-4/tp#44]
Any upcoming meeting will popup at the top of the Ui, to show the meeting to remind the insurance Agent.

**Comment by jimseah-0116** [comment]
As discussed, we will move reminders command to a later iteration.
I will make a 'meetings' command to view all meetings instead.

**Comment by jimseah-0116** [comment]
Meetings command successfully implemented.
No tests written for it yet, will do that soon.
